config/routes.rb
Rails.application.routes.draw do

get 'help' => 'static_pages#help'
  
get 'about' => 'static_pages#about'

get 'contact' => 'static_pages#contact'

get 'signup'  => 'users#new'

get  'login'   => 'sessions#new'

post 'login'   => 'sessions#create'

delete 'logout'  => 'sessions#destroy'

resources :users

  root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
    
# the regular expression for valid email
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

# remember digest that is used at the remember method, it is a symbol
attr_accessor :remember_token

before_save { self.email = email.downcase }

validates :name, presence: true, length: {maximum: 50}

validates :email, presence: true, length: {maximum: 255}, 
                    format: {with: VALID_EMAIL_REGEX},
                   uniqueness: true

has_secure_password

validates :password, presence: true, length: {minimum: 6}

# Returns the hash digest of the given string. To be used in testing
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

# Return the new token for the login process that has Remember me feature
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
# Associate a remember token with the user and saves the corresponding digest 
# in the db
  def remember
    self.remember_token = User.new_token # we use self. so that var can be global
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
# auth the remeber_token in the same way as has_secure_password feature
# for ad-hoc login by using bcrypt gem facilities
  def authenticated?(remember_token)
    return false if remember_digest.nil? # solve the bug of logging out in different browsera
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
include ApplicationHelper
include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # params [:session][:email] contains the email of the said session that
    # is tryng to login. The same can be said of the params [:session][:password]
    user = User.find_by(email: params[:session][:email].downcase)
    
    # auth via has_secure_password helper
    if user && user.authenticate(params[:session][:password])
      # Log the user in 
      log_in(user)
      # automatically remember the user with the code below
      #remember user # same as remember (user)
      # or, remember if the checkbox is clicked, thus getting 1 on the
      # params [][] hash value
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      # and redirect to the user's show page.
      redirect_to user
    
    else
      # Redirect the user when the login failed
      # Flash the message only once with flash.now
      flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
   # debugger
  end
 
  def new
    @user = User.new
  end
  
  def create
      @user = User.new(user_params)
    if @user.save
      # log the new user automatically
      log_in @user # @user same as user?
      # Handle a successful save.
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      # Handle a unsuccessful signup
      render 'new'
    end
  end


  private

    def user_params
    # mass assignement by using strong parametres
    # init a Ruby variable by using a hash of values
    # we require that the hash named params to have a attribute named user
    # and permit only name et al attributes to user attribute
    # an example of hash that contains hash values as well
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
      # We treat session as if it were a hash, with key-pair values.
      # :user_id is the key, user.id is the value
    session[:user_id] = user.id
    end
    
    def current_user
      # Get the current user in order to facilitate the display of the app pages
      # based on the user logged on (that can be id-ed by session[:user_id]). 
      # The code below is the same as:
      # if @current_user.nil?
      # @current_user = User.find_by(id: session[:user_id])
      # else
      # @current_user
      # or
      # @current_user = @current_user || User.find_by(id: session[:user_id])
      # code from last chapter
      # @current_user ||= User.find_by(id: session[:user_id])
      # the code below updates current user taking into account the remember me feature
      if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
       elsif cookies.signed[:user_id]
      # raise # This code line causes the test to raise an exception. 
      # If tests pass, it means that this branch is currently untested.
            user = User.find_by(id: cookies.signed[:user_id])
        if user && user.authenticated?(cookies[:remember_token])
            log_in user
            @current_user = user
        end
      end
    end
    
  def remember(user) # the remember me feature. the real work is done here
    user.remember # use method from sessions_helper to generate token
    # Save its user_id and remember_token cookies
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def log_out
      # logout process for the current user
    forget(current_user) # forget a permanent session/cookie
    session.delete(:user_id)
    @current_user = nil
    
  end
  
    def logged_in?
    # a helper method to enquire if said user is logged on or not
    !current_user.nil?
    end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget # this code is equiv of update_attribute(:remember_digest, nil), thus
                # resetting the remember_token
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def full_title(page_title = '')
     base_title = "Ruby on Rails Tutorial Sample App"
     if page_title.empty?
       base_title
     else page_title + '|' + base_title
     end
  end
end

app/helpers/user_helper.rb
module UserHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <!-- the clasees navbar et al have a special meaning in Bootstrap-->
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <!-- Ruby helper link_to linkes the # URL stub (which we can substitute
        later on) with the link text "sample app" and style it with CSS id "logo" -->
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
          <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
          <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--execute the following javascript source if IE browser is less than 9 -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html> <!--define the type of the html doc, for v.5 and up -->
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim'%>

  </head>
  <body>
   <%=render 'layouts/header'%>
  
    <div class="container">
        
        <!-- flash message as per their type to the main application layout -->
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
          
      <!--the yield method inserts the content of the page to the site layout -->
      <%= yield %>
    </div>
    
     <%= render 'layouts/footer' %>
     <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<!-- the jumbotron has a special meaning in Bootstrap -->
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
 
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<!--use the Ruby helper to link specified URL with image_tag where the rails.png
    is available localy. the alt attribute eanbles borwser to show the
    alternative text in case that the image is not shown -->
<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form_control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form_control'%>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form_control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form_control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>